### ISSUE TITLE
opam release

### ISSUE THREAD

**Issue by aantron** [ulrikstrid/ocaml-oidc#33]
Are there any plans to do an opam release soon? Just asking &mdash; could still work around this downstream using my much-overused rename-and-vendor workflow.

**Comment by ulrikstrid** [comment]
Yes, I think a 0.2.0 is due

**Comment by mizlan** [comment]
How does renaming-and-vendoring work?

**Comment by ulrikstrid** [comment]
1,5 years later we're almost there: https://github.com/ocaml/opam-repository/pull/27129
