### ISSUE TITLE
Pass nonce into `SimpleClient.valid_token_of_string`

### ISSUE THREAD

**Issue by mizlan** [ulrikstrid/ocaml-oidc#39]
`SimpleClient.valid_token_of_string` calls `Token.Response.validate`, and `Token.Response.validate` has the optional argument `nonce`, but `SimpleClient.valid_token_of_string` does not expose an argument `nonce` and hence the nonce cannot be checked to validate the token.

**Comment by anmonteiro** [comment]
can you propose a PR?

**Comment by mizlan** [comment]
Sure! I am still learning about OAuth and OIDC, and don't quite know the purpose a nonce serves, so it may be a bit before I submit a PR as I am still poking around and learning.

**Comment by ulrikstrid** [comment]
Looks like we can just thread it through with a `?nonce`

**Comment by mizlan** [comment]
Yes, sounds good. I couldn’t easily build the project, so please merge a
fix if possible.

Thank you for making this project!
